[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/refund-policy/"
  to = "/legales#cancelacion"
  status = 301
  force = true

[[redirects]]
  from = "/tag/segovia/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/tag/segovia/page/2/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/segovia-desde-el-aire-paseo-en-globo/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/a-que-altura-vuela-un-globo-curiosidades-que-te-sorprenderan/"
  to = "/articulos/como-se-dirige-globo"
  status = 301
  force = true

[[redirects]]
  from = "/producto/oferta-vuelo-en-globo-en-segovia/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/producto/*"
  to = "https://shop.voyagerballoons.eu/producto/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/etiqueta-producto/madrid/"
  to = "/vuelo-en-globo-segovia-desde-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/actividades-segovia.html"
  to = "/actividades-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-en-globo-segovia.html"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-en-globo-segovia-desde-madrid.html"
  to = "/vuelo-en-globo-segovia-desde-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/seguridad-pilotos.html"
  to = "/seguridad-pilotos"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/vuelo-globo-segovia.html"
  to = "/articulos/vuelo-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/primer-vuelo-globo.html"
  to = "/articulos/primer-vuelo-globo"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/regalar-vuelo-globo.html"
  to = "/articulos/regalar-vuelo-globo"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/como-se-dirige-globo.html"
  to = "/articulos/como-se-dirige-globo"
  status = 301
  force = true

[[redirects]]
  from = "/shop"
  to = "https://shop.voyagerballoons.eu/"
  status = 301
  force = true

[[redirects]]
  from = "/shop/*"
  to = "https://shop.voyagerballoons.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
