[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/regalar-vuelo-en-globo"
  to = "/regalar-vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/regalar-vuelo-en-globo/"
  to = "/regalar-vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/refund-policy/"
  to = "/legales#cancelacion"
  status = 301
  force = true

[[redirects]]
  from = "/about/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/nosotros/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/contacto/"
  to = "/#contacto"
  status = 301
  force = true

[[redirects]]
  from = "/contact/"
  to = "/#contacto"
  status = 301
  force = true

[[redirects]]
  from = "/home/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/en/home/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/it/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/pt/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/tag/segovia/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/tag/segovia/page/2/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/segovia-desde-el-aire-paseo-en-globo/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/a-que-altura-vuela-un-globo-curiosidades-que-te-sorprenderan/"
  to = "/articulos/como-se-dirige-globo"
  status = 301
  force = true

[[redirects]]
  from = "/guia-completa-para-volar-en-globo-aerostatico-en-segovia/"
  to = "/articulos/primer-vuelo-globo"
  status = 301
  force = true

[[redirects]]
  from = "/que-hacer-cerca-de-madrid-experiencia-segovia-5/"
  to = "/actividades-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/que-hacer-cerca-de-madrid-vuelo-en-globo-segovia"
  to = "/vuelo-en-globo-segovia-desde-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/la-experiencia-de-volar-en-globo/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/producto/oferta-vuelo-en-globo-en-segovia/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/comfort/"
  to = "/vuelo-en-globo-segovia-comfort"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-comfort/"
  to = "/vuelo-en-globo-segovia-comfort"
  status = 301
  force = true

[[redirects]]
  from = "/en/comfort/"
  to = "/en/comfort-hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/producto/*"
  to = "https://shop.voyagerballoons.eu/producto/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/categoria-producto/vuelos/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/etiqueta-producto/madrid/"
  to = "/vuelo-en-globo-segovia-desde-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/flights/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/zonas-de-vuelo/"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/flights/trip-search-result/"
  query = {view_mode = "grid"}
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/blog-2/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/author/equipo-voyager-balloons-eu/page/3/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/en/my-account/"
  to = "https://shop.voyagerballoons.eu/"
  status = 301
  force = true

[[redirects]]
  from = "/en/about/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/tag/vuelo-en-globo-segovia/"
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/tag/segovia/"
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/tag/volar-en-globo/"
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/etiqueta-producto/madrid/"
  to = "/en/hot-air-balloon-segovia-from-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/en/etiqueta-producto/segovia/"
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/categoria-producto/vuelos/"
  to = "/en/hot-air-balloon-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/en/category/informacion/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/category/uncategorized/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/wp-*.php"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/actividades-segovia.html"
  to = "/actividades-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-en-globo-segovia.html"
  to = "/vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/paseo-en-globo-segovia.html"
  to = "/paseo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/regalar-vuelo-en-globo-segovia.html"
  to = "/regalar-vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/regalar-vuelo-en-globo.html"
  to = "/regalar-vuelo-en-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-en-globo-segovia-desde-madrid.html"
  to = "/vuelo-en-globo-segovia-desde-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/vuelo-en-globo-madrid.html"
  to = "/vuelo-en-globo-madrid"
  status = 301
  force = true

[[redirects]]
  from = "/seguridad-pilotos.html"
  to = "/seguridad-pilotos"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/vuelo-globo-segovia.html"
  to = "/articulos/vuelo-globo-segovia"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/primer-vuelo-globo.html"
  to = "/articulos/primer-vuelo-globo"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/regalar-vuelo-globo.html"
  to = "/articulos/regalar-vuelo-globo"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/como-se-dirige-globo.html"
  to = "/articulos/como-se-dirige-globo"
  status = 301
  force = true

[[redirects]]
  from = "/articulos/que-hacer-en-braganza-portugal.html"
  to = "/articulos/que-hacer-en-braganza-portugal"
  status = 301
  force = true

[[redirects]]
  from = "/pt/o-que-fazer-em-braganca.html"
  to = "/pt/o-que-fazer-em-braganca"
  status = 301
  force = true

[[redirects]]
  from = "/en/things-to-do-in-braganca-portugal.html"
  to = "/en/things-to-do-in-braganca-portugal"
  status = 301
  force = true

[[redirects]]
  from = "/shop"
  to = "https://shop.voyagerballoons.eu/"
  status = 301
  force = true

[[redirects]]
  from = "/shop/*"
  to = "https://shop.voyagerballoons.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
